_prefs: 
  mapid: yassyass.3cc7c9c6
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 139.6775
  - 35.4216
  - 16
description: ''
format: "png8:m=h:c=32"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 3
name: ''
source: "tmsource:///Users/takeo/OSM/MapboxStyle/seadata.tm2source"
styles: 
  - semap.mss
  - light.mss
  - buoy.mss
template: ''
